(ns org.candelbio.alzabo.output
  (:require [clojure.pprint :as pprint]
            [clojure.java.io :as io]
            [me.raynes.fs :as fs]
            )
  )

(def header ";;; Automatically generated by Alzabo. Do not edit!")

(defn write-schema
  "Write the Alzabo or Datomic schema to a file"
  [alz-schema file]
  (println "Writing" file)
  (fs/mkdirs (fs/parent file))
  (with-open [w (io/writer file)]
    (binding [*print-length* nil
              *out* w]
      ;; TODO maybe indicate source (via dynamic variable?)
      (println header)
      (pprint/pprint alz-schema))))

